server:
  port: 8082
#  context-path: /autotest-portal

spring:
  application:
    name: autotest-portal

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver   # com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/autotest?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 138628
    type: com.alibaba.druid.pool.DruidDataSource
    
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
      
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true  
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

mybatis:
  mapperLocations: classpath:mybatis/*.xml

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
  
ribbon:  
  ReadTimeout: 500000  
  ConnectTimeout: 500000
  SocketTimeout: 500000